# Generated by Django 5.2 on 2025-04-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harpstroy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatorSubmission',
        ),
    ]
