# Generated by Django 5.2 on 2025-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harpstroy', '0002_delete_calculatorsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fence_length', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('gate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gate_count', models.CharField(blank=True, max_length=50, null=True)),
                ('installation', models.CharField(blank=True, max_length=100, null=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка с калькулятора',
                'verbose_name_plural': 'Заявки с калькулятора',
            },
        ),
    ]
